
eureka.client.serviceUrl.defaultZone:http://localhost:8761/eureka/


#swagger
springdoc.api-docs.enabled: true


spring.datasource.master.url=jdbc:mysql://127.0.0.1:3306/ai3_test?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci
spring.datasource.master.username=root
spring.datasource.master.password=wwgQRCm2%!D1c3AYGEqmdPDaFWryMOzt^Z
spring.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.master.hikari.maximum-pool-size=50
spring.datasource.master.hikari.minimum-idle=5
spring.datasource.master.hikari.idle-timeout=120000
spring.datasource.master.hikari.connection-timeout=30000
spring.datasource.master.hikari.max-lifetime=240000

spring.datasource.slave.url=jdbc:mysql://127.0.0.1:3306/ai3_test?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci
spring.datasource.slave.username=root
spring.datasource.slave.password=wwgQRCm2%!D1c3AYGEqmdPDaFWryMOzt^Z
spring.datasource.slave.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.slave.hikari.maximum-pool-size=50
spring.datasource.slave.hikari.minimum-idle=5
spring.datasource.slave.hikari.idle-timeout=120000
spring.datasource.slave.hikari.connection-timeout=30000
spring.datasource.slave.hikari.max-lifetime=240000

rw.separation.enabled=false


#redis
spring.data.redis.host=127.0.0.1
spring.data.redis.password=
spring.data.redis.port=6379
spring.data.redis.database=3

#async
thread.pool.corePoolSize=10
thread.pool.maxPoolSize=20
thread.pool.queueCapacity=200


#rabbit
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=ai
spring.rabbitmq.password=0PhoRxNoFwaKTaR81jHtINd03ru8reUPcXm
spring.rabbitmq.virtual-host=/

