
spring.profiles.active=dev

server.port=8093

spring.application.name=service-business

eureka.instance.prefer-ip-address=true
#eureka.instance.lease-expiration-duration-in-seconds=10
#eureka.instance.lease-renewal-interval-in-seconds=5
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true


logging.level.com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

mybatis.config-locations=classpath:mybatis/mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml

spring.main.allow-bean-definition-overriding=true

#swagger
springdoc.packages-to-scan: com.ai.servicebusiness.controller
server.forward-headers-strategy: framework

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=60s


