
eureka.client.serviceUrl.defaultZone:http://localhost:8761/eureka/


#swagger
springdoc.api-docs.enabled: false


#mysql
spring.datasource.master.url=jdbc:mysql://10.0.0.139:3306/ai_prod?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci
spring.datasource.master.username=ai_prod
spring.datasource.master.password=wwgQRCm2%!D1c3AYGEqmdPDaFWryMOzt^Z3
spring.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.master.hikari.maximum-pool-size=100
spring.datasource.master.hikari.minimum-idle=10
spring.datasource.master.hikari.idle-timeout=120000
spring.datasource.master.hikari.connection-timeout=30000
spring.datasource.master.hikari.max-lifetime=240000

spring.datasource.slave.url=jdbc:mysql://10.0.0.71:3306/ai_prod?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci
spring.datasource.slave.username=ai_prod
spring.datasource.slave.password=wwgQRCm2%!D1c3AYGEqmdPDaFWryMOzt^Z3
spring.datasource.slave.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.slave.hikari.maximum-pool-size=100
spring.datasource.slave.hikari.minimum-idle=10
spring.datasource.slave.hikari.idle-timeout=120000
spring.datasource.slave.hikari.connection-timeout=30000
spring.datasource.slave.hikari.max-lifetime=240000

rw.separation.enabled=true


#redis
spring.data.redis.host=127.0.0.1
spring.data.redis.password=e2u^Q17qNa4$Odp!htyooCfHXJD8gxLc6ec
spring.data.redis.port=6379
spring.data.redis.database=3

#async
thread.pool.corePoolSize=30
thread.pool.maxPoolSize=100
thread.pool.queueCapacity=300


#rabbit
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=ai
spring.rabbitmq.password=0PhoRxNoFwaKTaR81jHtINd03ru8reUPcXm
spring.rabbitmq.virtual-host=/