
spring.profiles.active=dev

logging.level.com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

mybatis.config-locations=classpath:mybatis/mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml

spring.application.name=base-websocket
eureka.instance.prefer-ip-address=true

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=60s

#mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.tomcat.initSQL=SET NAMES utf8mb4 COLLATE utf8mb4_general_ci
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=240000