
eureka.client.serviceUrl.defaultZone:http://10.0.0.44:8761/eureka/


#swagger
springdoc.api-docs.enabled: false


#redis
spring.data.redis.host=127.0.0.1
spring.data.redis.password=
spring.data.redis.port=6379
spring.data.redis.database=5

#async
thread.pool.corePoolSize=100
thread.pool.maxPoolSize=1000
thread.pool.queueCapacity=2000

#rabbit
spring.rabbitmq.host=10.0.0.44
spring.rabbitmq.port=5672
spring.rabbitmq.username=ai
spring.rabbitmq.password=0PhoRxNoFwaKTaR81jHtINd03ru8reUPcXm
spring.rabbitmq.virtual-host=/


tencent.accountId1=68371522
tencent.dataSourceId1=1217022336
tencent.accessToken1=e8a92cba9a764a15c6d6d93cdc440572

tencent.accountId2=68163161
tencent.dataSourceId2=1217013783
tencent.accessToken2=90379012f46b88b5873f0de7adf5d9e1

tencent.accountId3=68739069
tencent.dataSourceId3=1217163008
tencent.accessToken3=e022705db49520aead5b9771901a1a10

tencent.accountId4=66764770
tencent.dataSourceId4=1217162859
tencent.accessToken4=6ffefaec5d95ba87452156c9492a96a9

