
eureka.client.serviceUrl.defaultZone:http://10.0.0.119:8761/eureka/


#swagger
springdoc.api-docs.enabled: false


#redis
spring.data.redis.host=127.0.0.1
spring.data.redis.password=
spring.data.redis.port=6379
spring.data.redis.database=5

#async
thread.pool.corePoolSize=100
thread.pool.maxPoolSize=1000
thread.pool.queueCapacity=2000

#rabbit
spring.rabbitmq.host=10.0.0.119
spring.rabbitmq.port=5672
spring.rabbitmq.username=ai
spring.rabbitmq.password=0PhoRxNoFwaKTaR81jHtINd03ru8reUPcXm
spring.rabbitmq.virtual-host=/


tencent.accountId1=69475933
tencent.dataSourceId1=1217393355
tencent.accessToken1=2b9c541f2f557d70d25902b92b01be27

tencent.accountId2=a
tencent.dataSourceId2=a
tencent.accessToken2=a

tencent.accountId3=a
tencent.dataSourceId3=a
tencent.accessToken3=a

tencent.accountId4=a
tencent.dataSourceId4=a
tencent.accessToken4=a

