
eureka.client.serviceUrl.defaultZone:http://localhost:8761/eureka/


#swagger
springdoc.api-docs.enabled: true


#redis
spring.data.redis.host=127.0.0.1
spring.data.redis.password=
spring.data.redis.port=6379
spring.data.redis.database=3

#async
thread.pool.corePoolSize=10
thread.pool.maxPoolSize=20
thread.pool.queueCapacity=200


#rabbit
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=ai3
spring.rabbitmq.password=123456
spring.rabbitmq.virtual-host=ai3


tencent.accountId1=68371522
tencent.dataSourceId1=1217022336
tencent.accessToken1=e8a92cba9a764a15c6d6d93cdc440572

tencent.accountId2=68163161
tencent.dataSourceId2=1217013783
tencent.accessToken2=90379012f46b88b5873f0de7adf5d9e1

tencent.accountId3=68163161
tencent.dataSourceId3=1217013783
tencent.accessToken3=90379012f46b88b5873f0de7adf5d9e1

tencent.accountId4=68163161
tencent.dataSourceId4=1217013783
tencent.accessToken4=90379012f46b88b5873f0de7adf5d9e1
